bush:
  axiom: X
  rules:
    'X': F[+X]F[-X]+X
    'F': FF
  delta: 20.0

gramineae:
  axiom: F
  rules:
    'F': F[+F]F[-F][F]
  delta: 20.0

# TODO: add central start point
# - axiom: "F-F-F-F"
#   rules:
#     - F: "F-F+F+FF-F-F+F"
#   delta: 90
#   name: "quadratic_koch_island"
