heather:
  axiom: X
  rules:
    'X':
      - production: F[+X]F[-X]+X
    'F':
      - production: FF
  delta: 20.0

wild_carrot:
  axiom: F
  rules:
    'F': 
      - prob: 1
        production: F[+F]F[-F][F]
  delta: 20.0

stochastic_example:
  axiom: F
  rules:
    'F': 
      - prob: 0.33
        production: F[+F]F[-F][F]
      - prob: 0.33
        production: F[+F]F
      - prob: 0.34
        production: F[-F]

  delta: 20.0

bush:
  axiom: F
  rules:
    'F': 
    - prob: 0.9
      production: FF-[-F+F+F]+[+F-F-F]
    - prob: 0.1
      production: FF
  delta: 22.5

graminae:
  axiom: X
  rules:
    'X':
    - production: F-[[X]+X]+F[+FX]-X
    'F':
    - production: FF
  delta: 22.5

# need a central start point
# quadratic_koch_island:
#   axiom: "F-F-F-F"
#   rules:
#     'F': 
#     - production: "F-F+F+FF-F-F+F"
#   delta: 90
