heather:
  axiom: X
  rules:
    'X':
      - prob: 1
        production: F[+X]F[-X]+X
    'F':
      - prob: 1
        production: FF
  delta: 20.0

wild_carrot:
  axiom: F
  rules:
    'F': 
      - prob: 1
        production: F[+F]F[-F][F]
  delta: 20.0

stoch_example:
  axiom: F
  rules:
    'F': 
      - prob: 0.33
        production: F[+F]F[-F][F]
      - prob: 0.33
        production: F[+F]F
      - prob: 0.34
        production: F[-F]

  delta: 20.0

# bush:
#   axiom: F
#   rules:
#     'F': FF-[-F+F+F]+[+F-F-F]
#   delta: 22.5

# graminae:
#   axiom: X
#   rules:
#     'X': F-[[X]+X]+F[+FX]-X
#     'F': FF
#   delta: 22.5

# test_plant:
#   axiom: X
#   rules:
#     'X': F[+XF]-[F[+FXF]]
#     'F': FF[+F]
#   delta: 22.5

# TODO: add central start point
# - axiom: "F-F-F-F"
#   rules:
#     - F: "F-F+F+FF-F-F+F"
#   delta: 90
#   name: "quadratic_koch_island"
