# TODO: make this config file readable to load different lsystem
# TODO: check needed parameters

quadratic_koch_island:
  axiom: "F-F-F-F"
  rules:
    - F: "F-F+F+FF-F-F+F"
  delta: 90

plant1: # TODO: definitely find a better name
  axiom: "X"
  rules:
  - X: "F[+X]F[-X]+X"
  - F: "FF"
  delta: 20

plant2: